# kitty opens in center of screen
placement_strategy center

# zoom in/zoom out
map ctrl+shift+equal change_font_size all +2.0
map ctrl+shift+minus change_font_size all -2.0

# background transparency and blur
background_opacity 0.60
background_blur 60

# lowkey dont know what this does..
dynamic_background_opacity yes

font_size 22

